UI quiz screen
Practica-iOS-2021/Internship2022TeamSzabi pull request #23
Opened 2022-08-09 16:12 UTC by KuicsCristian

2022-08-09 16:16 UTC, iOSinternshipen requested changes

2022-08-09 16:16 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/QuizViewController/QuizCustomCell/QuizQuestionTableViewCell.swift
> +    @IBOutlet weak var quizContainer: UIView!
use private

2022-08-10 06:30 UTC, iOSinternshipen approved these changes

2022-08-10 07:28 UTC, IuliaRAnisoi reviewed
should delete the fixed height of the "Finish" button and instead select a "Large" size for it, from the Size Inspector (it's the first option)

2022-08-10 07:28 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/QuizViewController/QuizViewController.swift
> +                                                       for: indexPath) as? QuizQuestionTableViewCell else {
should remove extra space before "for" provided that SwiftLint shows no error

2022-08-10 07:28 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/QuizViewController/QuizCustomCell/QuizQuestionTableViewCell.swift
> +    override func awakeFromNib() {
should add extra line of space here

2022-08-10 07:28 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/QuizViewController/QuizCustomCell/QuizQuestionTableViewCell.swift
> +    @IBAction func buttonSelected(_ sender: UIButton) {
this should be private

2022-08-10 07:28 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/QuizViewController/QuizViewController.swift
> +                           forCellReuseIdentifier: QuizQuestionTableViewCell.identifier)
should remove extra space before argument name provided that SwiftLint shows no error

2022-08-10 08:36 UTC, IuliaRAnisoi approved these changes

2022-08-10 08:37 UTC, merged